exports.rules = [{
	regexp: /<([^>]+)>/g,
	replacement: "$1"
}, {
	regexp: /[|ˈ]/g,
	replacement: ""
}, {
	regexp: /ɡ/g,
	replacement: "gu"
}, {
	regexp: /aɪ/g,
	replacement: "ê"
}, {
	regexp: /ɔɪ|oɪ/g,
	replacement: "oi"
}, {
	regexp: /ɪə/g,
	replacement: "ire"
}, {
	regexp: /eɪ/g,
	replacement: "èy"
}, {
	regexp: /ɪ/g,
	replacement: "i"
}, {
	regexp: /oʊ/g,
	replacement: "au"
}, {
	regexp: /əʊ/g,
	replacement: "o"
}, {
	regexp: /ʊ/g,
	replacement: "ou"
}, {
	regexp: /ʌ/g,
	replacement: "o"
}, {
	regexp: /θ/g,
	replacement: "s"
}, {
	regexp: /ð/g,
	replacement: "z"
}, {
	regexp: /ɒ/g,
	replacement: "o"
}, {
	regexp: /uː/g,
	replacement: "ou"
// source: http://french.about.com/library/pronunciation/bl-ipa-french.htm
}, {
	regexp: /b/g,
	replacement: "B"
}, {
	regexp: /k/g,
	replacement: "K"
}, {
	regexp: /ʃ/g,
	replacement: "CH"
}, {
	regexp: /d/g,
	replacement: "D"
}, {
	regexp: /f/g,
	replacement: "F"
}, {
	regexp: /g/g,
	replacement: "G",
}, {
	regexp: /ʒ/g,
	replacement: "J"
}, {
	regexp: /h/g,
	replacement: "H"
}, {
	regexp: /ɲ/g,
	replacement: "NY"//"GN"
}, {
	regexp: /l/g,
	replacement: "L"
}, {
	regexp: /m/g,
	replacement: "M"
}, {
	regexp: /n/g,
	replacement: "N"
}, {
	regexp: /ŋ/g,
	replacement: "NGUE"
}, {
	regexp: /p/g,
	replacement: "P"
}, {
	regexp: /r/g,
	replacement: "R"
}, {
	regexp: /s/g,
	replacement: "S"
}, {
	regexp: /t/g,
	replacement: "T"
}, {
	regexp: /v/g,
	replacement: "V"
}, {
	regexp: /x/g,
	replacement: "RR"
}, {
	regexp: /z/g,
	replacement: "Z"
}, {
	regexp: /a/g,
	replacement: "A"
}, {
	regexp: /ɑ/g,
	replacement: "Â"
}, {
	regexp: /e/g,
	replacement: "É"
}, {
	regexp: /ɛ/g,
	replacement: "È"
}, {
	regexp: /ə/g,
	replacement: "E"
}, {
	regexp: /œ/g,
	replacement: "EU"
}, {
	regexp: /ø/g,
	replacement: "EU"
}, {
	regexp: /i/g,
	replacement: "I"
}, {
	regexp: /o/g,
	replacement: "O"
}, {
	regexp: /ɔ/g,
	replacement: "O"
}, {
	regexp: /u/g,
	replacement: "OU"
}, {
	regexp: /y/g,
	replacement: "U"
}, {
	regexp: /ɑ̃/g,
	replacement: "AN"
}, {
	regexp: /ɛ̃/g,
	replacement: "IN"
}, {
	regexp: /ɔ̃/g,
	replacement: "ON"
}, {
	regexp: /œ̃/g,
	replacement: "UN"
}, {
	regexp: /ʝ/g,
	replacement: "Y"
}, {
	regexp: /ɥ/g,
	replacement: "U"
}, {
	regexp: /w/g,
	replacement: "OU"
}]