exports.rules = [{
	regexp: /eks/g,
	replacement: "EX"
}, {
	regexp: /ɡ/g,
	replacement: "GU"
}, {
	regexp: /aɪ/g,
	replacement: "AILLE"
}, {
	regexp: /ɔɪ|oɪ/g,
	replacement: "OI"
}, {
	regexp: /ɪə/g,
	replacement: "IRE"
}, {
	regexp: /eɪ/g,
	replacement: "EILLE"
}, {
	regexp: /ɪ/g,
	replacement: "I"
}, {
	regexp: /oʊ/g,
	replacement: "AU"
}, {
	regexp: /əʊ/g,
	replacement: "AU"
}, {
	regexp: /ʊ/g,
	replacement: "OU"
}, {
	regexp: /ʌ/g,
	replacement: "O"
}, {
	regexp: /θ/g,
	replacement: "S"
}, {
	regexp: /ð/g,
	replacement: "Z"
}, {
	regexp: /ɒ/g,
	replacement: "O"
}, {
	regexp: /æ/g,
	replacement: "a"
}, {
	regexp: /ɑːr/g,
	replacement: "AR"
}, {
	regexp: /ɑː/g,
	replacement: "O"
}, {
	regexp: /r̩/g,
	replacement: "EUR"
//}, {
//	regexp: /uː/g,
//	replacement: "OU"
// source: http://french.about.com/library/pronunciation/bl-ipa-french.htm
}, {
	regexp: /b/g,
	replacement: "B"
}, {
	regexp: /k/g,
	replacement: "K"
}, {
	regexp: /ʃ/g,
	replacement: "CH"
}, {
	regexp: /d/g,
	replacement: "D"
}, {
	regexp: /f/g,
	replacement: "F"
}, {
	regexp: /g/g,
	replacement: "G",
}, {
	regexp: /ʒ/g,
	replacement: "J"
}, {
	regexp: /h/g,
	replacement: "H"
}, {
	regexp: /ɲ/g,
	replacement: "NY"//"GN"
}, {
	regexp: /l/g,
	replacement: "L"
}, {
	regexp: /m/g,
	replacement: "M"
}, {
	regexp: /n/g,
	replacement: "N"
}, {
	regexp: /ŋ/g,
	replacement: "NNEGUE"
}, {
	regexp: /p/g,
	replacement: "P"
}, {
	regexp: /r/g,
	replacement: "R"
}, {
	regexp: /s/g,
	replacement: "S"
}, {
	regexp: /t/g,
	replacement: "T"
}, {
	regexp: /v/g,
	replacement: "V"
}, {
	regexp: /x/g,
	replacement: "RR"
}, {
	regexp: /z/g,
	replacement: "Z"
}, {
	regexp: /a/g,
	replacement: "A"
}, {
	regexp: /ɑ/g,
	replacement: "A"//"Â"
}, {
	regexp: /e/g,
	replacement: "É"
}, {
	regexp: /ɛ/g,
	replacement: "È"
}, {
	regexp: /ə/g,
	replacement: "EU"
}, {
	regexp: /œ/g,
	replacement: "EU"
}, {
	regexp: /ø/g,
	replacement: "EU"
}, {
	regexp: /i/g,
	replacement: "I"
}, {
	regexp: /o/g,
	replacement: "O"
}, {
	regexp: /ɔ/g,
	replacement: "O"
}, {
	regexp: /u/g,
	replacement: "OU"
}, {
	regexp: /y/g,
	replacement: "U"
}, {
	regexp: /ɑ̃/g,
	replacement: "AN"
}, {
	regexp: /ɛ̃/g,
	replacement: "IN"
}, {
	regexp: /ɔ̃/g,
	replacement: "ON"
}, {
	regexp: /œ̃/g,
	replacement: "UN"
}, {
	regexp: /ʝ/g,
	replacement: "Y"
}, {
	regexp: /ɥ/g,
	replacement: "U"
}, {
	regexp: /w/g,
	replacement: "W"
}, {
	regexp: /[ː|ˈ<>]/g,
	replacement: ""
}]